// Package initialism provides a list of alternative spellings, acronyms and initialisms for the named releasers.
//
// Alternative spellings are the same name but with different casing, spelling or punctuation (e.g. Coca-Cola, Coke).
//
// An acronym is an abbreviation formed from the initial letters of other words and pronounced as a word (e.g. NATO).
//
// An initialism is an abbreviation consisting of the initial letters pronounced invidivually (e.g. USA).
package initialism

import "strings"

// A Path is the partial URL path of the releaser.
type Path string

// List is a map of initialisms to releasers.
type List map[Path][]string

// path keys that are too long for the initialism map.
const (
	crue    = "cheat-requests-for-the-underground-elite"
	nappa   = "north-american-pirate_phreak-association"
	neua    = "national-elite-underground-alliance"
	nuaa    = "national-underground-application-alliance"
	tdttrsi = "the-dream-team*tristar-ampersand-red-sector-inc"
	tlf     = "tristar-ampersand-red-sector-inc*lightforce*fusion"
)

// all initialisms should be in their stylized form.
var initialisms = List{
	"2000ad":                                {"2KAD", "2000 AD"},
	"8088-state":                            {"8088"},
	"aces-of-ansi-art":                      {"AAA"},
	"acid-productions":                      {"ACiD", "ANSi Creators in Demand"},
	"advanced-art-of-cracking-group":        {"AAOCG"},
	"advanced-pirate-technology":            {"APT"},
	"affinity":                              {"AFT"},
	"air":                                   {"Team AiR", "Addiction In Releasing"},
	"alpha-flight":                          {"AFL"},
	"ages":                                  {"AGS"},
	"amnesia":                               {"AMN"},
	"anemia":                                {"ANM"},
	"anti-security-agency":                  {"ASA"},
	"astalavista-group":                     {"ASTA"},
	"arab-team-4-reverse-engineering":       {"AT4RE"},
	"arrogant-couriers-with-essays":         {"ACE"},
	"art-of-reverse-engineering":            {"AORE"},
	"artists-in-revolt":                     {"AiR"},
	"attack-decay-sustain-release":          {"ADSR"},
	"backlash":                              {"BLH"},
	"bad-ass-dudes":                         {"BAD"},
	"bentley-sidwell-productions":           {"BSP"},
	"belly-are-kiss-attack":                 {"BAKA"},
	"blades-of-steel":                       {"BOS", "Blades"},
	"black-riders":                          {"BRD"},
	"black-squadron":                        {"BS"},
	"blaze":                                 {"BLZ"},
	"blizzard":                              {"BLZ", "blizz"},
	"bitchin-ansi-design":                   {"BAD"},
	"break-the-copyright":                   {"BTCR"},
	"boys-from-company-c":                   {"BCC"},
	"buds-biased-utils-report":              {"utils"},
	"canadian-pirates-inc":                  {"CPI"},
	"cd-images-for-the-elite":               {"CiFE"},
	"celerity-utilities-division":           {"CUD"},
	crue:                                    {"CRUE"},
	"chaos":                                 {"CHS"},
	"class":                                 {"CLS"},
	"classic":                               {"CLS"},
	"chemical-reaction":                     {"CRO"},
	"codex":                                 {"CDX"},
	"coolphat-vibez":                        {"CPHV"},
	"couriers-of-pirated-software":          {"COPS"},
	"courier-weektop-scorecard":             {"CWS"},
	"crackers-in-action":                    {"CIA"},
	"crackpl":                               {"CP"},
	"crack-in-morocco":                      {"CiM"},
	"creators-of-intense-art":               {"CIA"},
	"crude":                                 {"CRD"},
	"cyber-force":                           {"CF"},
	"cybercrime-international-network":      {"CCi", "CyberCrime Inc."},
	"darksiders":                            {"DS"},
	"da-breaker-crew":                       {"DBC"},
	"dagger":                                {"DGR"},
	"damn-excellent-ansi-design":            {"DeAD"},
	"damn-excellent-ansi-designers":         {"DeAD"}, // Correct
	"delirium-tremens-group":                {"DTG"},
	"dead-on-arrival":                       {"DOA"},
	"dead-pirates-society":                  {"DPS"},
	"defacto":                               {"DF"},
	"defacto2":                              {"DF2", "DF"},
	"defacto2net":                           {"DF2"},
	"demented-dimensions":                   {"DD"},
	"disire":                                {"DSR"},
	"deviance":                              {"DEV", "DVN"},
	"deviated":                              {"DVT"},
	"devotion":                              {"DEV", "devot"},
	"digerati":                              {"DGT"},
	"digital-artists-of-the-rare-kind":      {"DARK"},
	"direct-from-stars":                     {"DFS"},
	"distinct":                              {"DTC", "DTN"},
	"divide-by-zero":                        {"DBZ"},
	"divine":                                {"DVN"},
	"drunken-rom-group":                     {"DRG", "Drunken"},
	"drink-or-die":                          {"DOD"},
	"dvt":                                   {"Devotion", "TeamDVT"},
	"dynasty":                               {"DYN"},
	"dynamix":                               {"DNX"},
	"dytec":                                 {"DYT", "DTC"},
	"dvniso":                                {"Deviance"},
	"eagle-soft-incorporated":               {"ESI"},
	"ebola-virus-crew":                      {"EVC"},
	"eclipse":                               {"ECL"},
	"eximius":                               {"XMS"},
	"empire-of-darkness":                    {"EOD"},
	"embrace":                               {"EMB"},
	"empire":                                {"EMP"},
	"energy":                                {"NRG"},
	"equinox":                               {"EQX"},
	"esp-pirates":                           {"ESP"},
	"exterminators":                         {"TEX"},
	"fairlight":                             {"FLT"},
	"fairlight-dox":                         {"FDX", "FLTDOX"},
	"faith":                                 {"FTH"},
	"fantastic-4-cracking-group":            {"F4CG"},
	"fast-action-trading-elite":             {"fATE"},
	"fighting-for-fun":                      {"fff"},
	"fight-only-for-freedom":                {"FOFF"},
	"file-rappers":                          {"FR"},
	"flying-horse-cracking-force":           {"FHCF"},
	"future-crew":                           {"FC"},
	"future-brain-inc":                      {"FBi"},
	"fusion":                                {"FSN"},
	"genesis":                               {"GNS"},
	"glory":                                 {"Glory Couriers", "GL"},
	"gorgeous-ladies-of-warez":              {"GLOW"},
	"graphic-revolution-in-progress":        {"GRiP"},
	"elite-couriers-group":                  {"ECG"},
	"epsilon":                               {"EPS"},
	"fatal-connection":                      {"FC", "FATAL"},
	"friendship":                            {"FRD"},
	"fyllecell":                             {"FLC"},
	"ghost-riders":                          {"GRS"},
	"graphics-rendered-in-magnificence":     {"GRiM"},
	"hard-to-beat-team":                     {"HTB"},
	"halcyon":                               {"HLN"},
	"haze":                                  {"HZ"},
	"highroad":                              {"HR"},
	"hipe":                                  {"HPE"},
	"hoodlum":                               {"HLM"},
	"horizon":                               {"HZN"},
	"humble-dox":                            {"The Humble Guys DOX"},
	"hybrid":                                {"HYB"},
	"hype":                                  {"HYP"},
	"kalisto":                               {"KAL"},
	"kyrie-eleison":                         {"KE", "KEISO"},
	"kryn":                                  {"KRN"},
	"illusion":                              {"iLL"},
	"immersion":                             {"IMS"},
	"independent":                           {"IND", "individual"},
	"independent-crackers-union":            {"ICU"},
	"intension":                             {"ITN"},
	"insane-creators-enterprise":            {"iCE"},
	"international-network-of-crackers":     {"INC"},
	"international-cracking-crew":           {"iCC"},
	"inc-documentation-division":            {"IDD"},
	"inc-utility-division":                  {"IUD"},
	"influence":                             {"iNF"},
	"infinity":                              {"INF"},
	"jrp":                                   {"JRP"},
	"just-the-facts":                        {"JTF"},
	"laxity":                                {"LXT"},
	"legacy":                                {"LGC", "LGY"},
	"legend":                                {"LGD", "LEG"},
	"licensed-to-draw":                      {"LTD"},
	"light-speed-distributors":              {"LSD"},
	"lightforce":                            {"LFC", "LF"},
	"lithium":                               {"LIT"},
	"linezer0":                              {"Lz0", "Linezero"},
	"live-now-die-later":                    {"LnDL"},
	"lockless":                              {"LKL"},
	"lucid":                                 {"LCD"},
	"malicious-art-denomination":            {"MAD"},
	"malice":                                {"MAL"},
	"majic-12":                              {"M12"},
	"masters-of-the-art-experience":         {"MAX"},
	"millennium":                            {"MnM"},
	"mutual-assured-destruction":            {"MAD"},
	"manifest":                              {"MFD", "Manifest Destiny"},
	"motiv8":                                {"M8"},
	"mirage":                                {"MIR"},
	"myth*deviance":                         {"MDVN"},
	neua:                                    {"NEUA", "North Eastern Underground Alliance"},
	nuaa:                                    {"NUAA"},
	"napalm":                                {"NPM"},
	"nerve":                                 {"NRV"},
	"netrunners":                            {"NR"},
	"network-software-association":          {"NSA"},
	"new-york-crackers":                     {"NYC"},
	"nexus":                                 {"NXS", "NX"},
	"nokturnal-trading-alliance":            {"NTA"},
	nappa:                                   {"NAPPA"},
	"nrp":                                   {"NRP"},
	"oceanine":                              {"OCN"},
	"oddity":                                {"ODT"},
	"old-warez-inc":                         {"OWI"},
	"oneup":                                 {"1UP", "One Up"},
	"orion":                                 {"ORN"},
	"origin":                                {"OGN"},
	"originally-funny-guys":                 {"OFG"},
	"outcast":                               {"OUT"},
	"outlaws":                               {"OTL", "OUT"},
	"paradigm":                              {"PDM", "Zeus"},
	"paradox":                               {"PDX"},
	"pdm-iso":                               {"PDMISO", "Paradigm ISO"},
	"pentagram":                             {"PTG"},
	"phoenix":                               {"PHX"},
	"phrozen-crew":                          {"PC"},
	"pirates-analyze-warez":                 {"PAW"},
	"pirates-gone-crazy":                    {"PGC"},
	"pirates-sick-of-initials":              {"PSi"},
	"pirates-with-attitudes":                {"PWA"},
	"police":                                {"PLC"},
	"portable-apps-crew-europe":             {"PACE"},
	"prophecy":                              {"PCY"},
	"prozac":                                {"PRO"},
	"ptl-club":                              {"PTL"},
	"postmortem":                            {"PM"},
	"prestige":                              {"PSG", "PST"},
	"public-enemy":                          {"PE"},
	"public-enemy*red-sector-inc":           {"PE", "PE/RSI"},
	"quartex":                               {"QTX"},
	"razordox":                              {"RZR", "Razor"},
	"razor-1911":                            {"RZR", "Razor"},
	"razor-1911-cd-division":                {"RazorCD"},
	"razor-1911-demo":                       {"RZR", "Razor"},
	"reality-check-network":                 {"RCN"},
	"rebels":                                {"RBS"},
	"red-sector-inc":                        {"RSI"},
	"release-on-rampage":                    {"RoR"},
	"relic":                                 {"REL"},
	"reloaded":                              {"RLD"},
	"reflux":                                {"RLX"},
	"relentless-pursuit-of-magnificence":    {"RPM"},
	"request-to-send":                       {"RTS"},
	"resistance-is-futile":                  {"RiF"},
	"resurrection":                          {"RSR", "RES"},
	"revenge-crew":                          {"REV"},
	"reverse-2-revolutionize":               {"R2R"},
	"reverse-engineers-dream":               {"RED"},
	"reverse-engineering-in-software":       {"REiS"},
	"reverse-engineering-passion-team":      {"REPT"},
	"rise-in-superior-couriering":           {"RiSC"},
	"sanxion":                               {"SXN"},
	"seek-n-destroy":                        {"SND", "Seek and Destroy"},
	"skid-row":                              {"SR", "Skidrow"},
	"scoopex":                               {"SCX", "SPX"},
	"scandal":                               {"SCL"},
	"scienide":                              {"SCi"},
	"silicon-dream-artists":                 {"SDA"},
	"share-and-enjoy":                       {"SAE"},
	"shmeitcorp":                            {"Shmeit Corp", "SC"},
	"shitonlygerman":                        {"SOG", "Scheisse Deutsch Only"},
	"skillion":                              {"SKN"},
	"shiver":                                {"SHV"},
	"siege":                                 {"SG"},
	"sodom":                                 {"SDM"},
	"software-chronicles-digest":            {"SCD"},
	"software-pirates-inc":                  {"SPI"},
	"spazm":                                 {"SPZ", "SPZM", "Spazm/VGA", "Spazm Couriers"},
	"standards-of-piracy-association":       {"SPA"},
	"superior-art-creations":                {"SAC"},
	"surprise-productions":                  {"SP"},
	"team-edge":                             {"EDGE"},
	"team-technotrogens":                    {"TT3", "Team T3"},
	"the-bitter-end":                        {"TBE"},
	"the-cracking-answer":                   {"TCA"},
	"the-crazed-asylum":                     {"TCA"},
	"the-console-division":                  {"TCD"},
	"the-council":                           {"CNC"},
	"the-dream-team":                        {"TDT"},
	"the-dream-team*skid-row":               {"TDT/SR"},
	tdttrsi:                                 {"TDT/TRSi"},
	"the-faction":                           {"FACTION"},
	"the-firm":                              {"FiRM", "FRM"},
	"the-force-team":                        {"TFT"},
	"the-game-review":                       {"TGR"},
	"the-game-scene-chart":                  {"TGSC"},
	"the-grand-council":                     {"TGC"},
	"the-humble-guys":                       {"THG", "Humble"},
	"the-lamerz-group":                      {"TLG"},
	"the-millennium-group":                  {"TMG"},
	"the-net-monkey-weekly-report":          {"TNMWR"},
	"the-nova-team":                         {"TNT"},
	"the-one-and-only":                      {"TOAO"},
	"the-outlaws":                           {"TOL", "OL"},
	"the-players-club":                      {"TPC"},
	"the-reversers-ultimate-epidemic":       {"tRUE"},
	"the-reviewers-guild":                   {"TRG"},
	"the-sabotage-rebellion-hackers":        {"TSRh"},
	"the-silents":                           {"TSL"},
	"the-software-innovation-network":       {"SIN"},
	"the-sysops-association-network":        {"TSAN"},
	"the-unbiased-dox-report":               {"DR"},
	"the-underground-council":               {"UGC"},
	"the-untouchables":                      {"UNT"},
	"thg-fx":                                {"The Humble Guys FX"},
	"tristar":                               {"TRS"},
	"tristar-ampersand-red-sector-inc":      {"TRSi", "TRS", "Tristar"},
	"tyranny":                               {"TYR"},
	"ultra-tech":                            {"UT"},
	"under-seh-team":                        {"UST"},
	"union":                                 {"UNi"},
	"united-artist-association":             {"UAA"},
	"united-couriers":                       {"UC"},
	"united-cracking-force":                 {"UCF"},
	"united-group-international":            {"UGI"},
	"united-reverse-engineering-team":       {"URET"},
	"united-software-association*fairlight": {"USA/FLT"},
	"united-software-association":           {"USA"},
	"united-states-courier-report":          {"USCR"},
	"underpl":                               {"UPL"},
	"unleashed":                             {"UNL"},
	"untouchables":                          {"UNT"},
	"vendetta":                              {"VND"},
	"vengeance":                             {"VGN", "VEN"},
	"visions-of-reality":                    {"VOR"},
	"virility":                              {"VRL"},
	"vitality":                              {"VIT", "VTL"},
	"vortex":                                {"VXT"},
	"wave":                                  {"The Wave", "CNC"},
	"wicked":                                {"WKD"},
	"x_force":                               {"XF"},
	"xtreeme":                               {"XT"},
	"ypogeios":                              {"YGS"},
	"zero-waiting-time":                     {"ZWT"},
	"zone":                                  {"z0ne"},
	tlf:                                     {"TLF", "TRSI Lightforce Fusion"},
}

// Initialism returns the alternative spellings, acronyms and initialisms for the URL path.
// Or an empty slice if the URL path has no initialism.
//
// Example:
//
//	Initialism("the-firm") = []string{"FiRM, FRM"}
//	Initialism("defacto2") = []string{"DF2"}
func Initialism(path Path) []string {
	return initialisms[path]
}

// Initialisms returns the list of initialisms.
func Initialisms() List {
	return initialisms
}

// IsInitialism returns true if the URL path has an initialism.
//
// Example:
//
//	IsInitialism("the-firm") = true
//	IsInitialism("defacto2") = true
//	IsInitialism("some-random-bbs") = false
func IsInitialism(path Path) bool {
	_, ok := initialisms[path]
	return ok
}

// Join returns the alternative spellings, acronyms and initialisms for the
// URL path as a comma separated string.
// Or an empty string if the URL path has no initialism.
//
// Example:
//
//	Join("the-firm") = "FiRM, FRM"
//	Join("defacto2") = "DF2"
func Join(path Path) string {
	i := Initialism(path)
	if len(i) == 0 {
		return ""
	}
	return strings.Join(i, ", ")
}
