// Package initialism provides a list of alternative spellings, acronyms and initialisms for the named releasers.
//
// Alternative spellings are the same name but with different casing, spelling or punctuation (e.g. Coca-Cola, Coke).
//
// An acronym is an abbreviation formed from the initial letters of other words and pronounced as a word (e.g. NATO).
//
// An initialism is an abbreviation consisting of the initial letters pronounced invidivually (e.g. USA).
package initialism

import "strings"

// A Path is the partial URL path of the releaser.
type Path string

// List is a map of initialisms to releasers.
type List map[Path][]string

// path keys that are too long for the initialism map.
const (
	cpc2001 = "corporation-for-public-cybercasting-2001"
	crue    = "cheat-requests-for-the-underground-elite"
	nappa   = "north-american-pirate_phreak-association"
	neua    = "national-elite-underground-alliance"
	nuaa    = "national-underground-application-alliance"
	tlf     = "tristar-ampersand-red-sector-inc*lightforce*fusion"
	assign  = "all-softwares-spread-into-global-network"
	mgsci   = "monthly-gameboy-scene-charts-international"
	nasa    = "north-american-society-of-anarchists"
	quick   = "quality-underground-image-creation-kings"
)

// All initialisms should be in their stylized form and can include
// initialisms, acronyms, alternative spellings.
// Any case formatting should not be done here, they go in the name package.
// As this is a public repo, problematic named groups or initialisms should not be listed.
var initialisms = List{
	"2000ad":                                {"2KAD", "2000 AD"},
	"8088-state":                            {"8088"},
	"aces-of-ansi-art":                      {"AAA"},
	"acid-productions":                      {"ACiD", "ANSi Creators in Demand"},
	"addiction-in-releasing":                {"AiR"},
	"advanced-art-of-cracking-group":        {"AAOCG"},
	"advanced-pirate-technology":            {"APT"},
	"adrenalin":                             {"Adren"},
	"affinity":                              {"AFT"},
	"air":                                   {"Team AiR", "Addiction In Releasing"},
	"arkham":                                {"AKM"},
	"alpha-flight":                          {"AFL"},
	"ages":                                  {"AGS"},
	"against-software-protection":           {"ASP"},
	"aggression":                            {"ARN"},
	"amnesia":                               {"AMN"},
	"american-pirate-industries":            {"API"},
	"amplified-music-pirates":               {"AMP"},
	"anemia":                                {"ANM"},
	"anthrox":                               {"ATX"},
	"anti-security-agency":                  {"ASA"},
	assign:                                  {"ASSiGN"},
	"astalavista-group":                     {"ASTA"},
	"arab-team-4-reverse-engineering":       {"AT4RE"},
	"arrogant-couriers-with-essays":         {"ACE"},
	"art-of-reverse-engineering":            {"AORE"},
	"artists-in-revolt":                     {"AiR"},
	"atari-pirates-incorporated":            {"API"},
	"attack-decay-sustain-release":          {"ADSR"},
	"artists-without-loyality":              {"AWoL"},
	"arcane-corporate-elite":                {"ACE"},
	"backlash":                              {"BLH"},
	"bad-ass-dudes":                         {"BAD"},
	"bad-news":                              {"BAD"},
	"baywatch":                              {"BWH"},
	"bentley-sidwell-productions":           {"BSP"},
	"belly-are-kiss-attack":                 {"BAKA"},
	"blades-of-steel":                       {"BOS", "Blades"},
	"black-riders":                          {"BRD"},
	"black-squadron":                        {"BS"},
	"blaze":                                 {"BLZ"},
	"blizzard":                              {"BLZ", "blizz"},
	"blue-beta-3d":                          {"BB3D"},
	"bitchin-ansi-design":                   {"BAD"},
	"binaries":                              {"BiN"},
	"billionaire-boys-club":                 {"BBC"},
	"break-the-copyright":                   {"BTCR"},
	"brotherhood-of-warez":                  {"BOW"},
	"brotherhood-union":                     {"BHU"},
	"boys-from-company-c":                   {"BCC"},
	"buds-biased-utils-report":              {"utils"},
	"canadian-pirates-inc":                  {"CPI"},
	"cascada":                               {"CDA"},
	"cardinals":                             {"CDS"},
	"cd-images-for-the-elite":               {"CiFE"},
	"celerity-utilities-division":           {"CUD"},
	crue:                                    {"CRUE"},
	"chaos":                                 {"CHS"},
	"class":                                 {"CLS"},
	"classic":                               {"CLS"},
	"club-elan":                             {"CE", "Club Elán"},
	"chemical-reaction":                     {"CRO"},
	"chinese-software-distribution-network": {"CSDN"},
	"codex":                                 {"CDX"},
	"coolphat-vibez":                        {"CPHV"},
	"coop":                                  {"The Dream Team + Tristar + Red Sector Inc.", "The Co-op"},
	"conspiracy":                            {"CSY", "CPY"},
	"console-supply-iso":                    {"CSISO"},
	"copycats-inc":                          {"CCI"},
	"complete-obliteration-of-retail-enforcement": {"CORE"},
	cpc2001:                                {"C.P.C. 2001", "CPC", "CPC 2001"},
	"couriers-of-pirated-software":         {"COPS"},
	"couriers-of-proven-software":          {"COPS"},
	"courier-weektop-scorecard":            {"CWS"},
	"crack-report-weekly":                  {"CRW"},
	"crackers-in-action":                   {"CIA"},
	"crackpl":                              {"CP"},
	"crack-in-morocco":                     {"CiM"},
	"cracking-for-fun":                     {"CFF"},
	"cracking-101":                         {"C101"},
	"cracking-in-ocean":                    {"CiO"},
	"crazyworld":                           {"CZW"},
	"crime-syndicate-net":                  {"TCS"},
	"creators-of-intense-art":              {"CIA"},
	"crude":                                {"CRD"},
	"cti":                                  {"Crude & TDK iNC"},
	"cybrix":                               {"CBX", "Cybrix Couriering"},
	"cygnus":                               {"CYG"},
	"cybermail":                            {"CM"},
	"cyber-force":                          {"CF"},
	"cybercrime-international-network":     {"CCi", "CyberCrime Inc."},
	"darksiders":                           {"DS"},
	"da-breaker-crew":                      {"DBC"},
	"dbcdemo":                              {"DBC", "Da Breaker Crew Demo Division"},
	"dagger":                               {"DGR"},
	"damage-incorporated":                  {"Di"},
	"damn-excellent-ansi-design":           {"DeAD"},
	"damn-excellent-ansi-designers":        {"DeAD"}, // Correct
	"darkside-incorporated":                {"DSI"},
	"dark-towers-international":            {"DTI"},
	"delirium-tremens-group":               {"DTG"},
	"dead-memory":                          {"DM"},
	"dead-on-arrival":                      {"DOA"},
	"dead-pirates-society":                 {"DPS"},
	"defacto":                              {"DF"},
	"defacto2":                             {"DF2", "DF"},
	"defacto2net":                          {"DF2"},
	"defiant":                              {"DFT"},
	"demented-dimensions":                  {"DD"},
	"demon-release-crew":                   {"DRC"},
	"desperate-turk-crackers":              {"Desperate", "DP"},
	"digital-factory":                      {"DF"},
	"disire":                               {"DSR"},
	"dead-or-alive":                        {"DOA"},
	"deviance":                             {"DEV", "DVN"},
	"deviated":                             {"DVT"},
	"devotion":                             {"DEV", "devot"},
	"digerati":                             {"DGT"},
	"digital-artists-of-the-rare-kind":     {"DARK"},
	"digital-insanity":                     {"DI"},
	"digital-millennium-cracking-alliance": {"DMCA"},
	"digital-noise-alliance":               {"DNA"},
	"direct-from-stars":                    {"DFS"},
	"direction-simple-la-kamisole":         {"DSK"},
	"dimension":                            {"DMN"},
	"distinct":                             {"DTC", "DTN"},
	"dislocated-babes":                     {"DST"},
	"disassemblers-of-america":             {"DOA"},
	"distributors-of-classic-warez":        {"DCW"},
	"divide-by-zero":                       {"DBZ"},
	"divine":                               {"DVN"},
	"domination-in-couriering":             {"DiC"},
	"downtown-hackers-crew":                {"D.H Crew", "DHC"},
	"dreadloc":                             {"DLC"},
	"dream-team":                           {"DT"},
	"drunken-rom-group":                    {"DRG", "Drunken"},
	"drone":                                {"DRN"},
	"drink-or-die":                         {"DOD"},
	"dvt":                                  {"Devotion", "TeamDVT"},
	"dutch-computer-enterprise":            {"DCE"},
	"dynasty":                              {"DYN"},
	"dynamix":                              {"DNX"},
	"dytec":                                {"DYT", "DTC"},
	"dvniso":                               {"Deviance"},
	"eagle-soft-incorporated":              {"ESI"},
	"ebola-virus-crew":                     {"EVC"},
	"eclipse":                              {"ECL"},
	"east-coast-connection":                {"ECC"},
	"eximius":                              {"XMS"},
	"elite-carding-network":                {"ECN"},
	"empire-of-darkness":                   {"EOD"},
	"embrace":                              {"EMB"},
	"electro-magnetic-crackers":            {"EMC"},
	"electromotive-force":                  {"EMF"},
	"empire":                               {"EMP"},
	"emporio":                              {"EMP"},
	"end-of-file":                          {"EOF"},
	"energy":                               {"NRG"},
	"equinox":                              {"EQX"},
	"esprit-couriers":                      {"Esprit"},
	"esp-pirates":                          {"ESP"},
	"eternity":                             {"ETE"},
	"eithel":                               {"ETH"},
	"exceptional":                          {"XCP"},
	"excessive-force-crew":                 {"EFC"},
	"explosion":                            {"EPN"},
	"extreme":                              {"EXT"},
	"extreme-team":                         {"ET"},
	"exterminators":                        {"TEX"},
	"extreme-trading-crew":                 {"ETC"},
	"evidence":                             {"EVD"},
	"fairlight":                            {"FLT"},
	"fairlight-dox":                        {"FDX", "FLTDOX"},
	"faith":                                {"FTH"},
	"fallen":                               {"FLN"},
	"fatal":                                {"FTL"},
	"fatbastards":                          {"FB"},
	"fantastic-4-cracking-group":           {"F4CG"},
	"fast-action-trading-elite":            {"fATE"},
	"fatigued-couriers-network":            {"FCN"},
	"federal-cracking-consortium":          {"FCC"},
	"fighting-for-fun":                     {"fff"},
	"fight-only-for-freedom":               {"FOFF"},
	"file-rappers":                         {"FR"},
	"fistful-of-steel":                     {"FOS"},
	"five-o":                               {"Five 0"},
	"flying-horse-cracking-force":          {"FHCF"},
	"future-crew":                          {"FC"},
	"future-brain-inc":                     {"FBi"},
	"fusion":                               {"FSN"},
	"galactic-review":                      {"GALA"},
	"gencliq":                              {"GCT"},
	"german-cracking-group":                {"GCG"},
	"german-trading-alliance":              {"GTA"},
	"german-warez-alliance":                {"GWA"},
	"genesis":                              {"GNS"},
	"genesis-project":                      {"GP"},
	"guild-of-distributors":                {"GODS", "GDS"},
	"glory":                                {"Glory Couriers", "GL"},
	"god-damn-warez":                       {"GDW"},
	"gorgeous-ladies-of-warez":             {"GLOW"},
	"gothic":                               {"GTHC"},
	"graphic-revolution-in-progress":       {"GRiP"},
	"elite-couriers-group":                 {"ECG"},
	"epsilon":                              {"EPS"},
	"fatal-connection":                     {"FC", "FATAL"},
	"fawkes":                               {"FWK"},
	"fasiso":                               {"FAS"},
	"file-propulsion-system":               {"FPS"},
	"friendship":                           {"FRD"},
	"fyllecell":                            {"FLC"},
	"glorious-console-master-race":         {"GCMR"},
	"ghost-riders":                         {"GRS"},
	"god-of-war":                           {"GOW"},
	"graphics-rendered-in-magnificence":    {"GRiM"},
	"hard-to-beat-team":                    {"HTB"},
	"halcyon":                              {"HLN"},
	"haze":                                 {"HZ"},
	"highroad":                             {"HR"},
	"high-society":                         {"HS"},
	"high-voltage":                         {"HV", "VOLT"},
	"high-speed-couriers":                  {"HSC"},
	"high-tech-couriers":                   {"HTC"},
	"hipe":                                 {"HPE"},
	"hoodlum":                              {"HLM"},
	"hooligans":                            {"HGL"},
	"horizon":                              {"HZN"},
	"humble-dox":                           {"The Humble Guys DOX"},
	"hummers":                              {"HUM"},
	"hybrid":                               {"HYB"},
	"hysteria":                             {"HSA"},
	"hype":                                 {"HYP"},
	"kalisto":                              {"KAL"},
	"krackass":                             {"KASS"},
	"katharsis":                            {"KTS"},
	"knights-of-the-round-table":           {"KORT"},
	"kyrie-eleison":                        {"KE", "KEISO"},
	"kryn":                                 {"KRN"},
	"illuminatus":                          {"ILL"},
	"illusion":                             {"iLL"},
	"infinity-e_mag":                       {"INF"},
	"ifranian-rebellious-hackers":          {"IRH"},
	"immersion":                            {"IMS"},
	"independent":                          {"IND", "individual"},
	"independent-crackers-union":           {"ICU"},
	"independant-cracking-institute":       {"ICI", "Independent Cracking Institute"}, //nolint:misspell
	"indonesia-reversing-crew":             {"IRC"},
	"intension":                            {"ITN"},
	"insane-creators-enterprise":           {"iCE"},
	"international-network-of-crackers":    {"INC"},
	"inc-europe": {
		"INC", "International Network of Crackers"},
	"international-cracking-crew":     {"iCC"},
	"international-software-alliance": {"ISA"},
	"inc-documentation-division": {
		"IDD", "International Network of Crackers",
	},
	"inc-utility-division": {
		"IUD", "International Network of Crackers",
	},
	"image":                         {"IMG"},
	"imphobia":                      {"IMP"},
	"impact":                        {"IMP"},
	"influence":                     {"iNF"},
	"infinity":                      {"INF"},
	"information-liberation-league": {"ILL"},
	"insanity":                      {"Insan"},
	"inquisition":                   {"INQ"},
	"interceptor":                   {"INT"},
	"invisible":                     {"INV"},
	"iranian-crackers-association":  {"ICA"},
	"iridium-magazine":              {"IRIDI"},
	"jrp":                           {"JRP"},
	"justiso":                       {"JI"},
	"just-for-fun":                  {"JFF"},
	"just-for-phun":                 {"J4P"},
	"just-the-facts":                {"JTF"},
	"lamers-of-power":               {"LOP"},
	"lancelot":                      {"LANCE"},
	"lancelot-2":                    {"LANCE"},
	"laxity":                        {"LXT"},
	"legacy":                        {"LGC", "LGY"},
	"legend":                        {"LGD", "LEG"},
	"legends-never-die":             {"LND"},
	"legion-of-doom":                {"LOD"},
	"legion-of-hackers":             {"LOH"},
	"inferno":                       {"INF"},
	"licensed-to-draw":              {"LTD"},
	"light-speed-distributors":      {"LSD"},
	"light-speed-warez":             {"LSW"},
	"lightforce":                    {"LFC", "LF"},
	"lithium":                       {"LIT"},
	"linezer0":                      {"Lz0", "Linezero"},
	"live-now-die-later":            {"LnDL"},
	"lockless":                      {"LKL"},
	"local-courier-system":          {"LCS"},
	"los-angeles-sysops-alliance":   {"LASA"},
	"lucid":                         {"LCD"},
	"lucifer":                       {"LUC"},
	"malicious-art-denomination":    {"MAD"},
	"malice":                        {"MAL"},
	"majic-12":                      {"M12"},
	"magnificent-art-designers":     {"MAD"},
	"microcomputer-assembly-software-hackers": {"MASH"},
	"masters-of-the-art-experience":           {"MAX"},
	"masque":                                  {"MSQ"},
	"master-artists-guild-for-the-elite":      {"MAGE"},
	"mea-culpa":                               {"MC"},
	"menaceiisociety":                         {"MiiS"},
	"millenium":                               {"MnM"}, //nolint:misspell
	"mutual-assured-destruction":              {"MAD"},
	"manifest":                                {"MFD", "Manifest Destiny"},
	mgsci:                                     {"MGSCI"},
	"motiv8":                                  {"M8"},
	"mickey-mouse-club":                       {"MMC"},
	"mirage":                                  {"MIR"},
	"miami-cracking-machine":                  {"MCM"},
	"mindcrash":                               {"MC"},
	"modders-on-drugs":                        {"MOD"},
	"myth*deviance":                           {"MDVN"},
	"nah-kolor":                               {"NAH"},
	neua:                                      {"NEUA", "North Eastern Underground Alliance"},
	nuaa:                                      {"NUAA"},
	"napalm":                                  {"NPM"},
	"nerve":                                   {"NRV"},
	"netrunners":                              {"NR"},
	"network-software-association":            {"NSA"},
	"new-york-crackers":                       {"NYC"},
	"new-world-order":                         {"NWO"},
	"nexus":                                   {"NXS", "NX"},
	"nokturnal-trading-alliance":              {"NTA"},
	"noobs-reverser-team":                     {"NBR"},
	"nordic-engineering-corporation":          {"NEC"},
	"north-eastern-crackers":                  {"NEC"},
	nappa:                                     {"NAPPA", "NAP/PA"},
	"nintendo-backup-crew":                    {"NBC"},
	"nrp":                                     {"NRP"},
	nasa:                                      {"NASA"},
	"national-software-network":               {"NSN"},
	"norwegian-cracking-company":              {"NCC"},
	"noclass":                                 {"NoCLS", "CLS"},
	"oceanine":                                {"OCN"},
	"oddity":                                  {"ODT"},
	"old-warez-inc":                           {"OWI"},
	"oldskool":                                {"OS"},
	"oneup":                                   {"1UP", "One Up"},
	"orion":                                   {"ORN"},
	"origin":                                  {"OGN"},
	"originally-funny-guys":                   {"OFG"},
	"our-nefarious-endeavor":                  {"ONE"},
	"out-rage-pirates":                        {"ORP"},
	"outcast":                                 {"OUT"},
	"outlaws":                                 {"OTL", "OUT"},
	"overkill":                                {"OVL"},
	"p2psaurus":                               {"PS"},
	"paradigm":                                {"PDM", "Zeus"},
	"paradox":                                 {"PDX"},
	"pc_cracking-service":                     {"PC-CS", "PCCS"},
	"pdm-iso":                                 {"PDMISO", "Paradigm ISO"},
	"pe*trsi*tdt":                             {"Public Enemy + Tristar + Red Sector + The Dream Team"},
	"pentagram":                               {"PTG"},
	"pentium-force-team":                      {"PFT"},
	"persian-genius-team":                     {"PGteam"},
	"phoenix":                                 {"PHX"},
	"phreakerz-against-commerce":              {"PAC"},
	"phrozen-crew":                            {"PC"},
	"pirates-cove":                            {"PC"},
	"pirates-analyze-warez":                   {"PAW"},
	"pirates-gone-crazy":                      {"PGC"},
	"pirates-in-legion":                       {"PiL"},
	"pirates-sick-of-initials":                {"PSi"},
	"pirates-with-attitudes":                  {"PWA"},
	"pizza-dox":                               {"PizzaDOX"},
	"plate-steel-productions":                 {"PSP"},
	"police":                                  {"PLC"},
	"portable-apps-crew-europe":               {"PACE"},
	"predator-666":                            {"PRD666"},
	"primal":                                  {"PML"},
	"prophecy":                                {"PCY"},
	"prozac":                                  {"PRO"},
	"ptl-club":                                {"PTL"},
	"postmortem":                              {"PM"},
	"prestige":                                {"PSG", "PST"},
	"public-brand-software":                   {"PBS"},
	"public-enemy":                            {"PE"},
	"quartex":                                 {"QTX"},
	quick:                                     {"QUICK"},
	"really-awful-music":                      {"RAM"},
	"razordox":                                {"RZR", "Razor"},
	"razor-1911":                              {"RZR", "Razor"},
	"razor-1911-cd-division":                  {"RazorCD"},
	"razor-1911-demo":                         {"RZR", "Razor"},
	"real-life-then-scene":                    {"RLTS"},
	"real-crazy-artists":                      {"RCA"},
	"real-cocoheads":                          {"RC"},
	"reality-check-network":                   {"RCN"},
	"real-time-pirates":                       {"RTP"},
	"rebels":                                  {"RBS"},
	"rebels*2000ad":                           {"R2"},
	"recoil":                                  {"RCL"},
	"red-sector-inc":                          {"RSI"},
	"release-on-rampage":                      {"RoR"},
	"relic":                                   {"REL"},
	"reloaded":                                {"RLD"},
	"relativity":                              {"REV"},
	"reflux":                                  {"RLX"},
	"relentless-pursuit-of-magnificence": {
		"RPM",
		"Relentlessly Pursuing Magnificence"},
	"republic-banana":                       {"RB"},
	"request-to-send":                       {"RTS"},
	"renaissance":                           {"RNS", "RSS"},
	"resistance-is-futile":                  {"RiF"},
	"rescue-raider":                         {"RR", "RR INC"},
	"resurrection":                          {"RSR", "RES"},
	"revelation":                            {"RVL"},
	"revenge-crew":                          {"REV"},
	"revolution-project":                    {"RP"},
	"reverse-2-revolutionize":               {"R2R"},
	"reverse-engineers-dream":               {"RED"},
	"reverse-engineering-in-software":       {"REiS"},
	"reverse-engineering-passion-team":      {"REPT"},
	"revolution":                            {"RVL"},
	"rise-in-superior-couriering":           {"RiSC"},
	"risciso":                               {"RiSC"},
	"rom-1911":                              {"Razor 1911 CD-ROM Division"},
	"romkids":                               {"RMK"},
	"sanxion":                               {"SXN"},
	"saints-and-sinners-group":              {"SSG"},
	"seek-n-destroy":                        {"SND", "Seek and Destroy"},
	"scene-charts":                          {"SC"},
	"skid-row":                              {"SR", "Skidrow"},
	"scoopex":                               {"SCX", "SPX"},
	"scooby-snack-magazine":                 {"SSM"},
	"scandal":                               {"SCL"},
	"scenenotice":                           {"SCN"},
	"scienide":                              {"SCi"},
	"sea-shell-commando":                    {"SSC"},
	"serials-2000":                          {"S2K"},
	"silicon-dream-artists":                 {"SDA"},
	"share-and-enjoy":                       {"SAE"},
	"shmeitcorp":                            {"Shmeit Corp", "SC"},
	"shitonlygerman":                        {"SOG", "Scheisse Deutsch Only"},
	"skillion":                              {"SKN"},
	"shiver":                                {"SHV"},
	"siege":                                 {"SG"},
	"silent-cracking-force":                 {"SCF"},
	"silent-cracking-service":               {"SCS"},
	"sinister":                              {"SiN"},
	"slaves-of-pain":                        {"SoP"},
	"smokers-in-krime":                      {"SiK"},
	"society-of-sharing":                    {"SOS"},
	"society-of-suckers":                    {"SOS"},
	"sodom":                                 {"SDM"},
	"solitudes":                             {"SLT"},
	"sorcerers":                             {"SOR"},
	"software-chronicles-digest":            {"SCD"},
	"software-in-danger":                    {"SID"},
	"software-pirates-inc":                  {"SPI"},
	"spetznas":                              {"spetznaz"},
	"spazm":                                 {"SPZ", "SPZM", "Spazm/VGA"},
	"spazm-couriers":                        {"SPZ", "SPZM", "SPAZM"},
	"standards-of-piracy-association":       {"SPA"},
	"static":                                {"STC"},
	"superior-art-creations":                {"SAC"},
	"surprise-productions":                  {"SP"},
	"suicide-is-painless":                   {"SiP"},
	"talent-entertainment":                  {"TLN"},
	"team-edge":                             {"EDGE"},
	"team-technotrogens":                    {"TT3", "Team T3"},
	"tekno-rage-ampersand-pirasoft":         {"TRPS"},
	"the-artists-guild":                     {"TAG"},
	"the-black-star":                        {"TBS"},
	"the-bitter-end":                        {"TBE"},
	"the-brain-slayer":                      {"TBS"},
	"the-buyers-group":                      {"TBG"},
	"the-canadian-crackers":                 {"TCC"},
	"the-cracking-answer":                   {"TCA"},
	"the-crazed-asylum":                     {"TCA"},
	"the-cradle-traders":                    {"TCT"},
	"the-console-division":                  {"TCD"},
	"the-corporation":                       {"CORP"},
	"the-council":                           {"CNC"},
	"the-cracking-lords":                    {"TCL"},
	"the-damned-souls":                      {"TDS"},
	"the-dream-team":                        {"TDT"},
	"the-documentation-network":             {"TDN"},
	"the-dominators":                        {"DOM"},
	"the-elementals-piratelist":             {"TEP"},
	"the-elite-scripting-team":              {"TEST"},
	"the-faction":                           {"FACTION"},
	"the-firm":                              {"FiRM", "FRM"},
	"the-force-team":                        {"TFT"},
	"the-gameboy-charts":                    {"GCharts"},
	"the-gamers-edge":                       {"TGE"},
	"the-game-review":                       {"TGR"},
	"the-game-scene-chart":                  {"TGSC"},
	"the-guild-of-thieves":                  {"TGT"},
	"the-grand-council":                     {"TGC"},
	"the-hardened-criminals":                {"THC"},
	"the-hill-people":                       {"THP"},
	"the-humble-guys":                       {"THG", "Humble"},
	"the-illinois-pirates":                  {"TIP"},
	"the-internet-dream-team":               {"TiDT"},
	"the-lamerz-group":                      {"TLG"},
	"the-inner-circle":                      {"TIC"},
	"the-lightning-crew":                    {"TLC"},
	"the-missing-link":                      {"TML"},
	"the-millennium-group":                  {"TMG"},
	"the-nameless-ones":                     {"TNO"},
	"the-naked-truth-magazine":              {"NTM"},
	"the-net-monkey-weekly-report":          {"TNMWR"},
	"the-north-west-connection":             {"TNWC"},
	"the-nova-team":                         {"TNT"},
	"the-one-and-only":                      {"TOAO"},
	"the-outlaws":                           {"TOL", "OL"},
	"the-pirate-syndicate":                  {"TPS"},
	"the-pirates-manifesto":                 {"Manifest"},
	"the-pirate-world":                      {"TPW"},
	"the-players-club":                      {"TPC"},
	"the-phoney-coders":                     {"TPC"},
	"the-reversers-ultimate-epidemic":       {"tRUE"},
	"the-reviewers-guild":                   {"TRG"},
	"the-red-scorpion":                      {"TRS"},
	"the-reservoir-warez-report":            {"Report"},
	"the-sabotage-rebellion-hackers":        {"TSRh"},
	"the-safety-zone":                       {"TSZ"},
	"the-space-pigs":                        {"SP"},
	"the-stealth-pirate-network":            {"TSPN"},
	"the-silents":                           {"TSL"},
	"the-software-innovation-network":       {"SIN"},
	"the-sinister-syndicate":                {"TSS"},
	"the-sure-logic-syndicate":              {"SLS"},
	"the-sysops-association-network":        {"TSAN"},
	"the-unbiased-dox-report":               {"DR"},
	"the-underground-council":               {"UGC"},
	"the-untouchables":                      {"UNT"},
	"the-warez-alliance":                    {"TWA"},
	"the-warez-report":                      {"Ware"},
	"the-warez-collectors":                  {"TWC"},
	"the-warez-magazine":                    {"Warez"},
	"the-week-in-warez":                     {"WWN"},
	"the-wondertwins":                       {"TWT"},
	"thg-fx":                                {"The Humble Guys FX"},
	"tired-of-protection":                   {"TOP"},
	"triad":                                 {"TRI"},
	"tristar":                               {"TRS"},
	"tristar-ampersand-red-sector-inc":      {"TRSi", "TRS", "Tristar"},
	tlf:                                     {"TLF", "TRSi/Lightforce/Fusion"},
	"twilight":                              {"TW"},
	"twilight-designs-crew":                 {"TDC"},
	"tyranny":                               {"TYR"},
	"ultra-tech":                            {"UT"},
	"ultra-force":                           {"UF", "Ultraforce"},
	"under-seh-team":                        {"UST"},
	"underground-empire":                    {"UE"},
	"union":                                 {"UNi"},
	"united-albanian-reverse-engineers":     {"UARE"},
	"united-artist-association":             {"UAA"},
	"united-couriers":                       {"UC"},
	"united-cracking-force":                 {"UCF"},
	"united-group-international":            {"UGI"},
	"united-reverse-engineering-team":       {"URET"},
	"united-software-association*fairlight": {"USA/FLT"},
	"united-software-association":           {"USA"},
	"united-states-courier-report":          {"USCR"},
	"underpl":                               {"UPL"},
	"underground-kidz":                      {"UK"},
	"unleashed":                             {"UNL"},
	"unpacking-gods":                        {"UG"},
	"untouchables":                          {"UNT"},
	"velocity-couriers":                     {"VEL"},
	"vendetta":                              {"VND"},
	"vengeance":                             {"VGN", "VEN", "Vengeance"},
	"vengeance-couriers":                    {"VGN"},
	"vertex":                                {"VTX"},
	"victoria-independent-piracy":           {"VIP"},
	"vital-dox":                             {"VD"},
	"vision-factory":                        {"VF"},
	"visions-of-reality":                    {"VOR"},
	"virility":                              {"VRL"},
	"vitality":                              {"VIT", "VTL"},
	"vortex":                                {"VXT"},
	"vortex-software":                       {"Vortex"},
	"warez-anarchy-review":                  {"WAR"},
	"wave":                                  {"The Wave", "CNC"},
	"warrior":                               {"WAR"},
	"wdyl-wtn":                              {"WDYL"},
	"west-coast-cracking-production":        {"WCCP"},
	"wicked":                                {"WKD"},
	"wizard-couriers":                       {"WC"},
	"world-wide-couriers":                   {"WWC"},
	"x_large":                               {"XL"},
	"x_factor":                              {"XFactor"},
	"x_force":                               {"XF"},
	"xtreeme":                               {"XT"},
	"ypogeios":                              {"YGS"},
	"zero-waiting-time":                     {"ZWT"},
	"zenith":                                {"ZNTH"},
	"zone":                                  {"z0ne"},
}

// Initialism returns the alternative spellings, acronyms and initialisms for the URL path.
// Or an empty slice if the URL path has no initialism.
//
// Example:
//
//	Initialism("the-firm") = []string{"FiRM, FRM"}
//	Initialism("defacto2") = []string{"DF2"}
func Initialism(path Path) []string {
	return initialisms[path]
}

// Initialisms returns the list of initialisms.
func Initialisms() List {
	return initialisms
}

// IsInitialism returns true if the URL path has an initialism.
//
// Example:
//
//	IsInitialism("the-firm") = true
//	IsInitialism("defacto2") = true
//	IsInitialism("some-random-bbs") = false
func IsInitialism(path Path) bool {
	_, ok := initialisms[path]
	return ok
}

// Join returns the alternative spellings, acronyms and initialisms for the
// URL path as a comma separated string.
// Or an empty string if the URL path has no initialism.
//
// Example:
//
//	Join("the-firm") = "FiRM, FRM"
//	Join("defacto2") = "DF2"
func Join(path Path) string {
	i := Initialism(path)
	if len(i) == 0 {
		return ""
	}
	return strings.Join(i, ", ")
}

// Match returns the list of initialisms that match the given string.
func Match(s string) []Path {
	var matches []Path
	for k, vals := range initialisms {
		for _, v := range vals {
			if strings.EqualFold(v, s) {
				matches = append(matches, k)
			}
		}
	}
	return matches

}
