// Package initialism provides a list of alternative spellings, acronyms and initialisms for the named releasers.
//
// Alternative spellings are the same name but with different casing, spelling or punctuation (e.g. Coca-Cola, Coke).
//
// An acronym is an abbreviation formed from the initial letters of other words and pronounced as a word (e.g. NATO).
//
// An initialism is an abbreviation consisting of the initial letters pronounced invidivually (e.g. USA).
package initialism

import (
	"maps"
	"slices"
	"strings"
)

// A Path is the partial URL path of the releaser.
type Path string

// List is a map of initialisms to releasers.
type List map[Path][]string

// path keys that are too long for the initialism map.
const (
	cpc2001 = "corporation-for-public-cybercasting-2001"
	core    = "complete-obliteration-of-retail-enforcement"
	crue    = "cheat-requests-for-the-underground-elite"
	epix    = "empire-of-pirate-intelligence-and-experts"
	mash    = "microcomputer-assembly-software-hackers"
	nappa   = "north-american-pirate_phreak-association"
	neua    = "national-elite-underground-alliance"
	nuaa    = "national-underground-application-alliance"
	iirg    = "international-information-retrieval-guild"
	jest    = "jolly-good-elites-traders-and-suppliers"
	tlf     = "tristar-ampersand-red-sector-inc*lightforce*fusion"
	assign  = "all-softwares-spread-into-global-network"
	mgsci   = "monthly-gameboy-scene-charts-international"
	nasa    = "north-american-society-of-anarchists"
	nnan    = "national-network-of-anarchists-and-nihilists"
	quick   = "quality-underground-image-creation-kings"
	rampage = "revolutionary-art-masters-pummeling-art-groups-everywhere"
	scud    = "sound-creators-and-unfailing-digitalizers"
	hate    = "highly-artistically-talented-enterprises"
	tsep    = "twilight-software-engineering-and-pirating"
	mcsci   = "monthly-console-scene-charts-international"
	nwo     = "new-world-order-computer-underground-magazine"
)

// Initialisms returns the list of initialisms.
//
// All initialisms should be in their stylized form and can include
// initialisms, acronyms, alternative spellings.
//
//   - Any casing and formatting should *not* be done here, those go in the [releaser/name] package.
//   - This is a public repo so commonsense problematic named groups or initialisms should not be listed.
//   - In Go, the order of the List map keys is randomized and has no performance impact.
//
// [releaser/name]: https://github.com/Defacto2/releaser/name
func Initialisms() List { //nolint:maintidx
	return List{
		"scd_dox":                                {"SCD", "Software Chronicles Digest / Dox Division"},
		"needful-things":                         {"NT"},
		"one-man-courier":                        {"OMC"},
		"no-bullshit-couriering":                 {"NBC"},
		"north-american-release-coalition":       {"NARC"},
		"dual-module-player":                     {"DMP"},
		"global-overdose":                        {"GOD"},
		"new-order":                              {"NO"},
		"butthole-surfers":                       {"BH"},
		"lightning-force":                        {"LF"},
		"psychosquad":                            {"PSD"},
		"rage-against-the-machine":               {"RAM"},
		"wankers-from-wimbledon":                 {"WW"},
		"mental-design":                          {"MD"},
		"jammin-the-airwaves":                    {"JTA"},
		"never-at-rest-couriers":                 {"NARC"},
		"siac":                                   {"SiÆC"},
		"syndicated-network-of-couriers":         {"SyNC"},
		"sliver-art-products":                    {"SAP"},
		"virtual-shock":                          {"VS"},
		"5th-dynasty":                            {"5D"},
		"paradigm-press":                         {"prdgm"},
		"corosion":                               {"COR"}, //nolint:misspell
		"warriors-against-software-protection":   {"WASP"},
		"no-lamerz-allowed":                      {"NLA"},
		"anoxia":                                 {"ANX"},
		"north-american-pirates":                 {"NAP"},
		"avengers":                               {"AVG"},
		"computer-pirate-syndicate":              {"CPS", "CP$"},
		"visual-simulations-inc":                 {"VSI"},
		"the-golden-triangle":                    {"TGT"},
		"the-newcomers":                          {"TNC"},
		"china-syndrome-inc":                     {"CSI"},
		"housetek":                               {"HTK"},
		"outlaws-exchange":                       {"OX"},
		"syndromes-mega-utility-team":            {"SMUT"},
		"entity":                                 {"ntt"},
		"ntt":                                    {"NTT"},
		"quick-silver":                           {"QSR", "QuickSilver"},
		"pyrodex":                                {"PRX", "Pyrodex PC Division"},
		"psychedelic-excretion-international":    {"PEi", "Psychdelic Excretion International"},
		"xtreemer":                               {"XT"},
		"top-curry-group":                        {"TCG"},
		"just-the-facts-handheld-edition":        {"JTF"},
		"weekly-wanking-stats":                   {"WWS"},
		"pocketheaven":                           {"PH"},
		"just-week-stats":                        {"JWS"},
		"some-weekly-chart":                      {"SWC"},
		"who-owned-weekly":                       {"WoW"},
		"the-marshall-mussolini-show":            {"TMMS"},
		"weekly-courier-stats-report":            {"WCSR"},
		"the-tobacco-brothers":                   {"TTBC"},
		"orgasming-gaming-magazine":              {"ORGAS"},
		"monthly-cracking-report":                {"MCR"},
		"zero-second-report":                     {"0SR"},
		"unbiased-courier-report":                {"UCR"},
		"the-big-picture-courier-report":         {"TBP"},
		"prozacs-personal-gaming-report":         {"PPGR"},
		"gameboycolor-world-charts":              {"GBWC", "GBC World"},
		"dextrose-chart":                         {"DX"},
		"couriers-weekly":                        {"CW"},
		"corrupt-console-diskmag":                {"CORR"},
		"actual-factual-couring":                 {"AfC"},
		"frontline-scene-release-report":         {"FTL"},
		"future-scene-news":                      {"FSN"},
		"nuclear-crackers":                       {"NC"},
		nwo:                                      {"NWO"},
		"scene-top-traders":                      {"STT"},
		"weekly-courier-report":                  {"WCR"},
		"top-telnet-traders-weekly":              {"TTW"},
		"the-legendary-report":                   {"TLR"},
		"resistance":                             {"RSE"},
		mcsci:                                    {"MCSCI"},
		"zenith-zine":                            {"ZZ"},
		"canadian-born-coders":                   {"CBC"},
		"virus-laboratories-and-distribution":    {"VLAD"},
		"higher-mental-plane":                    {"hmp"},
		"dutch-trader-charts":                    {"DTC"},
		"bbs-and-users-digest":                   {"BAUD"},
		"trip-2-hell":                            {"T2h"},
		"strictly-pirates":                       {"SP", "SP!"},
		"software-runners-from-hell":             {"SRH"},
		"software-pirates-alliance":              {"SPA"},
		"rebels-of-telecommunications":           {"ROT"},
		"quality-control-reviews":                {"QC"},
		"evolution-magazine":                     {"EVO", "EVOL"},
		"digital-press":                          {"DP"},
		"bizarre-types-of-wares":                 {"BTW"},
		"underground-experts-united":             {"UXU"},
		"the-review-crew":                        {"TRC"},
		"poison-control":                         {"PCi"},
		"magick":                                 {"MGK", "MUDD", "M.U.D.D.", "Magick Utilities & Demo's Division"},
		"infinity-93":                            {"INF"},
		"foundation":                             {"FDN"},
		"thhg":                                   {"The Hugo Husten Group", "The Horrible Hackers from Germany"},
		"2000ad":                                 {"2KAD", "2000 AD"},
		"8088-state":                             {"8088"},
		"aces-of-ansi-art":                       {"AAA"},
		"acid-productions":                       {"ACiD", "ANSi Creators in Demand"},
		"addiction-in-releasing":                 {"AiR"},
		"advanced-art-of-cracking-group":         {"AAOCG"},
		"advanced-pirate-technology":             {"APT"},
		"advanced-software-accessories":          {"ASA", "Advantage Software Accessories"},
		"adrenalin":                              {"Adren"},
		"affinity":                               {"AFT"},
		"aegis-corp":                             {"AGS"},
		"air":                                    {"Team AiR", "Addiction In Releasing"},
		"arkham":                                 {"AKM"},
		"alpha-flight":                           {"AFL"},
		"ages":                                   {"AGS"},
		"against-software-protection":            {"ASP"},
		"aggression":                             {"ARN", "AGS"},
		"amnesia":                                {"AMN"},
		"american-pirate-industries":             {"API"},
		"amplified-music-pirates":                {"AMP"},
		"anemia":                                 {"ANM"},
		"ansi-requires-talent":                   {"ART"},
		"anti-warez-association":                 {"AWA"},
		"anthrox":                                {"ATX"},
		"anti-security-agency":                   {"ASA"},
		"anti-lamers-foundation":                 {"ALF"},
		"anarchy-international-production":       {"AIP"},
		"ansi-factory":                           {"AFC"},
		assign:                                   {"ASSiGN"},
		"association-of-software-conspiracy":     {"ASC"},
		"astalavista-group":                      {"ASTA"},
		"arab-team-4-reverse-engineering":        {"AT4RE"},
		"arrogant-couriers-with-essays":          {"ACE"},
		"art-of-reverse-engineering":             {"AORE"},
		"artists-in-revolt":                      {"AiR"},
		"argies-courier-united":                  {"ACU"},
		"atari-pirates-incorporated":             {"API"},
		"atlantic-trading-alliance":              {"ATA"},
		"attack-decay-sustain-release":           {"ADSR"},
		"artists-without-loyality":               {"AWoL"},
		"arcane-corporate-elite":                 {"ACE"},
		"backlash":                               {"BLH"},
		"bad-ass-dudes":                          {"BAD"},
		"bad-news":                               {"BAD"},
		"baywatch":                               {"BWH"},
		"bentley-sidwell-productions":            {"BSP"},
		"belly-are-kiss-attack":                  {"BAKA"},
		"beverly-hills-boys":                     {"BHB"},
		"blades-of-steel":                        {"BOS", "Blades"},
		"black-out":                              {"BLOT"},
		"black-riders":                           {"BRD"},
		"black-squadron":                         {"BS"},
		"blaze":                                  {"BLZ"},
		"blizzard":                               {"BLZ", "blizz"},
		"blue-beta-3d":                           {"BB3D"},
		"bitchin-ansi-design":                    {"BAD"},
		"binaries":                               {"BiN"},
		"billionaire-boys-club":                  {"BBC"},
		"break-the-copyright":                    {"BTCR"},
		"brotherhood-of-warez":                   {"BOW"},
		"brotherhood-union":                      {"BHU"},
		"boys-from-company-c":                    {"BCC"},
		"bonzai":                                 {"BNZ"},
		"buds-biased-utils-report":               {"utils"},
		"bytegarden":                             {"BTG"},
		"canadian-pirates-inc":                   {"CPI"},
		"cancer":                                 {"CNC"},
		"car-e-lee":                              {"CEL"},
		"cascada":                                {"CDA"},
		"cardinals":                              {"CDS"},
		"cd-images-for-the-elite":                {"CiFE"},
		"celerity-utilities-division":            {"CUD"},
		crue:                                     {"CRUE"},
		"chaos":                                  {"CHS"},
		"class":                                  {"CLS"},
		"classic":                                {"CLS"},
		"classic-cracking-corporation":           {"CCC"},
		"club-elan":                              {"CE", "Club Elán"},
		"chaos-cyber-creations":                  {"CCC"},
		"chemical-reaction":                      {"CRO"},
		"chinese-software-distribution-network":  {"CSDN"},
		"codex":                                  {"CDX"},
		"coders-task-force":                      {"CTF"},
		"coolphat-vibez":                         {"CPHV"},
		"coop":                                   {"The Dream Team + Tristar + Red Sector Inc.", "The Co-op"},
		"community-of-moral-advancement":         {"COMA", "CMA"},
		"conspiracy":                             {"CSY", "CPY"},
		"contour":                                {"CTR"},
		"console-supply-iso":                     {"CSISO"},
		"console-gaming-informers":               {"CGI"},
		"copycats-inc":                           {"CCI"},
		"copyright-infiltration-agency":          {"CIA"},
		"corruption":                             {"COR"},
		"corporate-graphics":                     {"CGX"},
		"corrupted-programming-international":    {"CPI"},
		"criminals-of-radical-extremes":          {"CORE"},
		core:                                     {"CORE"},
		cpc2001:                                  {"C.P.C. 2001", "CPC", "CPC 2001"},
		"couriers-of-pirated-software":           {"COPS"},
		"couriers-of-proven-software":            {"COPS"},
		"courier-weektop-scorecard":              {"CWS"},
		"couriers-of-darkness":                   {"COD"},
		"crack-report-weekly":                    {"CRW"},
		"cowboys-from-hell":                      {"CFH"},
		"crackers-and-hackers-anonymous":         {"CHA"},
		"crackers-in-action":                     {"CIA"},
		"crackers-international-alliance":        {"CIA", "Crackers Int'l Alliance"},
		"crackpl":                                {"CP"},
		"crack-in-morocco":                       {"CiM"},
		"cracking-for-fun":                       {"CFF"},
		"cracking-101":                           {"C101"},
		"cracking-in-ocean":                      {"CiO"},
		"crackers-ampersand-whackers":            {"C&W", "CW"},
		"crazyworld":                             {"CZW"},
		"creeping-death-software":                {"CDS"},
		"crime-syndicate-net":                    {"TCS"},
		"crystal-phasematics":                    {"CPM"},
		"cryptonics-crew":                        {"CTC"},
		"creators-of-intense-art":                {"CIA"},
		"creators-of-revolutionary-pictures":     {"CORP"},
		"crude":                                  {"CRD"},
		"cti":                                    {"Crude & TDK iNC"},
		"cybrix":                                 {"CBX", "Cybrix Couriering"},
		"cygnus":                                 {"CYG"},
		"cybermail":                              {"CM"},
		"cyber-force":                            {"CF"},
		"cyber-legion":                           {"CL"},
		"cybercrime-international-network":       {"CCi", "CyberCrime Inc."},
		"darksiders":                             {"DS"},
		"da-breaker-crew":                        {"DBC"},
		"dbcdemo":                                {"DBC", "Da Breaker Crew Demo Division"},
		"dagger":                                 {"DGR"},
		"damage-incorporated":                    {"Di"},
		"damn-excellent-ansi-design":             {"DeAD"},
		"damn-excellent-ansi-designers":          {"DeAD"}, // Correct
		"darkside-incorporated":                  {"DSI"},
		"dark-towers-international":              {"DTI"},
		"delirium-tremens-group":                 {"DTG"},
		"dead-memory":                            {"DM"},
		"dead-on-arrival":                        {"DOA"},
		"dead-pirates-society":                   {"DPS"},
		"decrepit-old-geezers":                   {"DOG"},
		"defacto":                                {"DF"},
		"defacto2":                               {"DF2", "DF"},
		"defacto2net":                            {"DF2"},
		"defiant":                                {"DFT"},
		"demented-dimensions":                    {"DD"},
		"delirium-of-disorder":                   {"DoD"},
		"demon-release-crew":                     {"DRC"},
		"desperate-turk-crackers":                {"Desperate", "DP"},
		"destined-masters-of-zines":              {"DMZ"},
		"digital-factory":                        {"DF"},
		"disciples-of-private-enterprise":        {"DOPE"},
		"disciples-of-the-dark-knight":           {"DDK"},
		"disire":                                 {"DSR"},
		"dead-weight":                            {"DW"},
		"dead-or-alive":                          {"DOA"},
		"deviance":                               {"DEV", "DVN"},
		"deviated":                               {"DVT"},
		"devotion":                               {"DEV", "devot"},
		"digerati":                               {"DGT"},
		"digital-artists-of-the-rare-kind":       {"DARK"},
		"digital-insanity":                       {"DI"},
		"digital-millennium-cracking-alliance":   {"DMCA"},
		"digital-noise-alliance":                 {"DNA"},
		"direct-from-stars":                      {"DFS"},
		"direction-simple-la-kamisole":           {"DSK"},
		"dimension":                              {"DMN"},
		"distinct":                               {"DTC", "DTN"},
		"dislocated-babes":                       {"DST"},
		"disassemblers-of-america":               {"DOA"},
		"distributors-of-classic-warez":          {"DCW"},
		"divide-by-zero":                         {"DBZ"},
		"divine":                                 {"DVN"},
		"domination-in-couriering":               {"DiC"},
		"downtown-hackers-crew":                  {"D.H Crew", "DHC"},
		"dreadloc":                               {"DLC"},
		"dream-team":                             {"DT"},
		"dream-syndicate":                        {"DS"},
		"drunken-rom-group":                      {"DRG", "Drunken"},
		"drone":                                  {"DRN"},
		"drink-or-die":                           {"DOD"},
		"dvt":                                    {"Devotion", "TeamDVT"},
		"deadly-underground-network-of-elites":   {"DUNE"},
		"dutch-computer-enterprise":              {"DCE"},
		"doc-writers-inc":                        {"DWI"},
		"dynasty":                                {"DYN"},
		"dynamix":                                {"DNX"},
		"dytec":                                  {"DYT", "DTC"},
		"dvniso":                                 {"Deviance"},
		"eagle-soft-incorporated":                {"ESI"},
		"ebola-virus-crew":                       {"EVC"},
		"eclipse":                                {"ECL"},
		"east-coast-connection":                  {"ECC"},
		"eximius":                                {"XMS"},
		"extasy":                                 {"EX"},
		"exodus-couriers":                        {"Exodus Couriering"},
		"elite-carding-network":                  {"ECN"},
		"empire-of-darkness":                     {"EOD"},
		"embrace":                                {"EMB"},
		"electro-magnetic-crackers":              {"EMC"},
		"electromotive-force":                    {"EMF"},
		"electronic-rats":                        {"ECR"},
		"empire":                                 {"EMP"},
		"emporio":                                {"EMP"},
		"end-of-file":                            {"EOF"},
		"energy":                                 {"NRG"},
		epix:                                     {"EPIX"},
		"equinox":                                {"EQX"},
		"esprit-couriers":                        {"Esprit"},
		"esp-pirates":                            {"ESP"},
		"eternity":                               {"ETE"},
		"eithel":                                 {"ETH"},
		"excess":                                 {"ECS"},
		"exceptional":                            {"XCP"},
		"excessive-force-crew":                   {"EFC"},
		"explosion":                              {"EPN"},
		"extinct":                                {"EX"},
		"extreme":                                {"EXT"},
		"extreme-team":                           {"ET"},
		"extreme-graphix-alliance":               {"XGA"},
		"exterminators":                          {"TEX"},
		"extreme-trading-crew":                   {"ETC"},
		"evidence":                               {"EVD"},
		"euphoria":                               {"EPH"},
		"fairlight":                              {"FLT"},
		"fairlight-dox":                          {"FDX", "FLTDOX", "FAIRDOX"},
		"faith":                                  {"FTH"},
		"fallen":                                 {"FLN"},
		"fatal":                                  {"FTL"},
		"fatbastards":                            {"FB"},
		"fantastic-4-cracking-group":             {"F4CG"},
		"fast-action-trading-elite":              {"fATE"},
		"faster-than-light-couriers":             {"FLC"},
		"fatigued-couriers-network":              {"FCN"},
		"federal-cracking-consortium":            {"FCC"},
		"fast-elite-distributors-of-software":    {"FEDS"},
		"fighting-for-fun":                       {"fff"},
		"fight-only-for-freedom":                 {"FOFF"},
		"file-rappers":                           {"FR"},
		"fistful-of-steel":                       {"FOS"},
		"five-o":                                 {"Five 0"},
		"flying-horse-cracking-force":            {"FHCF"},
		"free-on-the-line":                       {"FOTL"},
		"freelancers-guild":                      {"FRL"},
		"fucked-beyond-repair":                   {"FBR"},
		"future-crew":                            {"FC"},
		"future-brain-inc":                       {"FBi"},
		"futuristic-artists-with-talent":         {"FAT"},
		"fusion":                                 {"FSN"},
		"galactic-review":                        {"GALA"},
		"game-release-list":                      {"Releases by Claude Rains"},
		"grave-yard-crew":                        {"GYC"},
		"gencliq":                                {"GCT"},
		"german-cracking-group":                  {"GCG"},
		"german-consoles-syndicate":              {"GCS"},
		"german-trading-alliance":                {"GTA"},
		"german-warez-alliance":                  {"GWA"},
		"genesis-ppe":                            {"GNS"},
		"genesis":                                {"GNS"},
		"genesis-project":                        {"GP"},
		"guild-of-distributors":                  {"GODS", "GDS"},
		"glory":                                  {"Glory Couriers", "GL"},
		"god-damn-warez":                         {"GDW"},
		"gorgeous-ladies-of-warez":               {"GLOW"},
		"gothic":                                 {"GTHC"},
		"goofy-illitape-softwarez":               {"GIS"},
		"graphic-revolution-in-progress":         {"GRiP"},
		"grand-old-pirates":                      {"GOP"},
		"elite-couriers-group":                   {"ECG"},
		"epsilon":                                {"EPS"},
		"fatal-connection":                       {"FC", "FATAL"},
		"fawkes":                                 {"FWK"},
		"fasiso":                                 {"FAS"},
		"file-propulsion-system":                 {"FPS"},
		"friendship":                             {"FRD", "Friends"},
		"federation-of-free-traders":             {"FOFT"},
		"fyllecell":                              {"FLC"},
		"future-ansi-creations":                  {"FAiC"},
		"graphically-enhanced-magazine":          {"GEM"},
		"glorious-console-master-race":           {"GCMR"},
		"ghost-riders":                           {"GRS"},
		"god-of-war":                             {"GOW"},
		"graphics-rendered-in-magnificence":      {"GRiM"},
		"gainseville-pirates-association":        {"GPA"},
		"hard-to-beat-team":                      {"HTB"},
		"hard-core-hackers":                      {"hCh"},
		"halcyon":                                {"HLN"},
		"hackers-with-attitude":                  {"HWA"},
		hate:                                     {"HaTe"},
		"hearts-in-the-shadows":                  {"HiTS"},
		"hardcore-elite-mother-phuckers":         {"HEMP", "HMP"},
		"haze":                                   {"HZ"},
		"highroad":                               {"HR"},
		"high-society":                           {"HS"},
		"high-voltage":                           {"HV", "HVC", "VOLT"},
		"high-speed-couriers":                    {"HSC"},
		"high-tech-couriers":                     {"HTC"},
		"high-speed-global-mass-trading":         {"HSGMT"},
		"hipe":                                   {"HPE"},
		"hoodlum":                                {"HLM"},
		"hooligans":                              {"HGL"},
		"horizon":                                {"HZN"},
		"humble-dox":                             {"The Humble Guys DOX"},
		"hummers":                                {"HUM"},
		"hybrid":                                 {"HYB"},
		"hysteria":                               {"HSA"},
		"hype":                                   {"HYP"},
		"keen-like-frogs":                        {"KLF"},
		"kryptonic-hacking-team":                 {"KHT"},
		"kalisto":                                {"KAL"},
		"krackass":                               {"KASS"},
		"katharsis":                              {"KTS"},
		"kosmic-loader-foundation":               {"KLF"},
		"knights-of-the-round-table":             {"KORT"},
		"kyrie-eleison":                          {"KE", "KEISO"},
		"kryn":                                   {"KRN"},
		"idiots-creations-unlimited":             {"iCU"},
		"illuminatus":                            {"ILL"},
		"illusion":                               {"iLL"},
		"infinity-e_mag":                         {"INF"},
		"ifranian-rebellious-hackers":            {"IRH"},
		iirg:                                     {"IIRG"},
		"immersion":                              {"IMS"},
		"independent":                            {"IND", "individual"},
		"independent-crackers-union":             {"ICU"},
		"independant-cracking-institute":         {"ICI", "Independent Cracking Institute"}, //nolint:misspell
		"indonesia-reversing-crew":               {"IRC"},
		"intension":                              {"ITN"},
		"insane-creators-enterprise":             {"iCE"},
		"international-ghost-hunters":            {"IGH"},
		"international-network-of-crackers":      {"INC"},
		"inc-europe":                             {"INC", "International Network of Crackers"},
		"international-cracking-crew":            {"iCC"},
		"international-software-alliance":        {"ISA"},
		"inc-documentation-division":             {"IDD", "International Network of Crackers"},
		"inc-utility-division":                   {"IUD", "International Network of Crackers"},
		"interpol":                               {"IPL"},
		"image":                                  {"IMG"},
		"imphobia":                               {"IMP"},
		"impact":                                 {"IMP"},
		"influence":                              {"iNF"},
		"infinity":                               {"INF"},
		"infinity-trainers-unlimited":            {"ITU"},
		"information-liberation-league":          {"ILL"},
		"international-software-traders":         {"IST"},
		"insanity":                               {"Insan"},
		"inquisition":                            {"INQ"},
		"interceptor":                            {"INT"},
		"invisible":                              {"INV"},
		"iranian-crackers-association":           {"ICA"},
		"iridium-magazine":                       {"IRIDI"},
		"jrp":                                    {"JRP"},
		jest:                                     {"JEST"},
		"justiso":                                {"JI"},
		"just-for-fun":                           {"JFF", "J4F", "Just 4 Fun"},
		"just-for-phun":                          {"J4P"},
		"just-the-facts":                         {"JTF"},
		"lamers-of-power":                        {"LOP"},
		"lancelot":                               {"LANCE"},
		"lancelot-2":                             {"LANCE"},
		"llange-art-reptareeko":                  {"LAR"},
		"last-poets-society":                     {"LPS"},
		"laxity":                                 {"LXT"},
		"lethal-software-distributors":           {"LSD"},
		"legacy":                                 {"LGC", "LGY"},
		"legend":                                 {"LGD", "LEG", "Legend PC"},
		"legends-never-die":                      {"LND"},
		"legion-of-doom":                         {"LOD", "LOH", "LOD/H"},
		"legion-of-dynamic-discord":              {"LODD"},
		"legion-of-rising-distributors":          {"LORD"},
		"inferno":                                {"INF"},
		"licensed-to-draw":                       {"LTD"},
		"little-big-one":                         {"LBO"},
		"light-speed-distributors":               {"LSD"},
		"light-speed-warez":                      {"LSW"},
		"lightforce":                             {"LFC", "LF"},
		"lithium":                                {"LIT"},
		"linezer0":                               {"Lz0", "Linezero"},
		"live-now-die-later":                     {"LnDL"},
		"lockless":                               {"LKL"},
		"legion-of-the-etherial":                 {"LOTE"},
		"local-courier-system":                   {"LCS"},
		"living-organisms-on-mars":               {"LOOM"},
		"los-angeles-sysops-alliance":            {"LASA"},
		"lucid":                                  {"LCD"},
		"lucifer":                                {"LUC"},
		"mack-crack-corporation":                 {"MCC"},
		"masters-of-abstractions-and-illusions":  {"MAi"},
		"malicious-art-denomination":             {"MAD"},
		"malondorous-griffin-entanglement":       {"MGE"},
		"malice":                                 {"MAL"},
		"majic-12":                               {"M12"},
		"magnificent-art-designers":              {"MAD"},
		mash:                                     {"MASH"},
		"masters-of-the-art-experience":          {"MAX"},
		"masque":                                 {"MSQ"},
		"master-artists-guild-for-the-elite":     {"MAGE"},
		"mea-culpa":                              {"MC"},
		"medeival-emporium-of-warez":             {"MEOW"}, //nolint:misspell
		"menaceiisociety":                        {"MiiS"},
		"millenium":                              {"MnM"}, //nolint:misspell
		"mutual-assured-destruction":             {"MAD"},
		"manifest":                               {"MFD", "Manifest Destiny"},
		mgsci:                                    {"MGSCI"},
		"mercury":                                {"MERC"},
		"more-stupid-initials":                   {"MSI"},
		"motiv8":                                 {"M8"},
		"micropirates-inc":                       {"MPI"},
		"mickey-mouse-club":                      {"MMC"},
		"mirage":                                 {"MIR"},
		"miami-cracking-machine":                 {"MCM"},
		"mindcrash":                              {"MC"},
		"modders-on-drugs":                       {"MOD"},
		"myth-inc":                               {"M.Y.T.H. Inc", "MYTH Inc Link BBS"},
		"myth*deviance":                          {"MDVN"},
		"nah-kolor":                              {"NAH"},
		neua:                                     {"NEUA", "North Eastern Underground Alliance"},
		nuaa:                                     {"NUAA"},
		"napalm":                                 {"NPM"},
		"national-crackers-alliance":             {"NCA"},
		"national-distribution-network":          {"NDN"},
		nnan:                                     {"NNAN"},
		"nerve":                                  {"NRV"},
		"netrunners":                             {"NR"},
		"network-software-association":           {"NSA"},
		"new-york-crackers":                      {"NYC"},
		"new-world-order":                        {"NWO"},
		"nexus":                                  {"NXS", "NX"},
		"nemesis":                                {"NMS"},
		"nokturnal-trading-alliance":             {"NTA"},
		"no-fear":                                {"NF"},
		"noobs-reverser-team":                    {"NBR"},
		"nordic-engineering-corporation":         {"NEC"},
		"north-eastern-crackers":                 {"NEC"},
		nappa:                                    {"NAPPA", "NAP/PA", "NAPE"},
		"nintendo-backup-crew":                   {"NBC"},
		"nrp":                                    {"NRP"},
		nasa:                                     {"NASA"},
		"nc_17":                                  {"NC"},
		"national-software-network":              {"NSN"},
		"norwegian-cracking-company":             {"NCC"},
		"noclass":                                {"NoCLS", "CLS"},
		"not-productions":                        {"NOT!"},
		"objectile":                              {"OCT"},
		"oceanine":                               {"OCN"},
		"oddity":                                 {"ODT"},
		"old-warez-inc":                          {"OWI"},
		"oldskool":                               {"OS"},
		"old-school-pirates":                     {"OSP"},
		"oneup":                                  {"1UP", "One Up"},
		"on_line-revenge":                        {"OLR", "Online Revenge"},
		"orion":                                  {"ORN"},
		"origin":                                 {"OGN"},
		"originally-funny-guys":                  {"OFG"},
		"our-nefarious-endeavor":                 {"ONE"},
		"out-rage-pirates":                       {"ORP"},
		"outcast":                                {"OUT"},
		"outlaws":                                {"OTL", "OUT"},
		"overkill":                               {"OVL"},
		"p2psaurus":                              {"PS"},
		"pirates-against-purchasing-software":    {"PAPS"},
		"partners-in-crime":                      {"PiC"},
		"paradigm":                               {"PDM", "Zeus"},
		"paradox":                                {"PDX"},
		"pc_cracking-service":                    {"PC-CS", "PCCS"},
		"pdm-iso":                                {"PDMISO", "Paradigm ISO"},
		"pe*trsi*tdt":                            {"Public Enemy + Tristar + Red Sector + The Dream Team"},
		"pentagram":                              {"PTG"},
		"pentium-force-team":                     {"PFT"},
		"persian-genius-team":                    {"PGteam"},
		"phoenix":                                {"PHX"},
		"phreakerz-against-commerce":             {"PAC"},
		"pirates-club-inc":                       {"PC INC"},
		"phrozen-crew":                           {"PC"},
		"pirates-cove":                           {"PC"},
		"pirates-analyze-warez":                  {"PAW"},
		"pirates-gone-crazy":                     {"PGC"},
		"pirates-in-legion":                      {"PiL"},
		"pirates-sick-of-initials":               {"PSi"},
		"pirates-with-attitudes":                 {"PWA"},
		"pirates-releasing-in-mass-extremes":     {"PRiME"},
		"pizza-dox":                              {"PizzaDOX"},
		"plate-steel-productions":                {"PSP"},
		"police":                                 {"PLC"},
		"power-crisis-international":             {"PCI"},
		"portable-apps-crew-europe":              {"PACE"},
		"psycho-corporate-productions":           {"PCP"},
		"predator-666":                           {"PRD666"},
		"primal":                                 {"PML"},
		"prophecy":                               {"PCY"},
		"propaganda":                             {"PROP"},
		"prozac":                                 {"PRO"},
		"ptl-club":                               {"PTL"},
		"postmortem":                             {"PM"},
		"prestige":                               {"PSG", "PST"},
		"protection-fucking-sucks":               {"PFS"},
		"psycho-squad":                           {"PSD"},
		"public-brand-software":                  {"PBS"},
		"public-enemy":                           {"PE"},
		"pyradical":                              {"PYR"},
		"quartex":                                {"QTX"},
		quick:                                    {"QUICK"},
		"radical-elite-movement":                 {"REM"},
		"really-awful-music":                     {"RAM"},
		"rage":                                   {"Rage'94"},
		"razordox":                               {"RZR", "Razor"},
		"razor-1911":                             {"RZR", "Razor"},
		"razor-1911-cd-division":                 {"RazorCD"},
		"razor-1911-demo":                        {"RZR", "Razor"},
		"real-life-then-scene":                   {"RLTS"},
		"real-crazy-artists":                     {"RCA"},
		"real-cocoheads":                         {"RC"},
		"reality-check-network":                  {"RCN"},
		"real-time-pirates":                      {"RTP"},
		"rebels":                                 {"RBS"},
		"r2":                                     {"R2", "RTWO"},
		"recoil":                                 {"RCL"},
		"red-sector-inc":                         {"RSI"},
		"red-green-blue":                         {"RGB"},
		"release-on-rampage":                     {"RoR"},
		"relic":                                  {"REL"},
		"reloaded":                               {"RLD"},
		"relativity":                             {"REV"},
		"reflux":                                 {"RLX"},
		"relentless-pursuit-of-magnificence":     {"RPM", "Relentlessly Pursuing Magnificence"},
		"republic-banana":                        {"RB"},
		"request-to-send":                        {"RTS"},
		"renaissance":                            {"RNS", "RSS"},
		"reign-of-terror":                        {"RoT"},
		"resistance-is-futile":                   {"RiF"},
		"rescue-raider":                          {"RR", "RR INC", "TDI"},
		"resurrection":                           {"RSR", "RES"},
		"revelation":                             {"RVL"},
		"review-of-aquired-warez":                {"RAW"}, //nolint:misspell
		"revenge-crew":                           {"REV"},
		"revolution-project":                     {"RP"},
		"reverse-2-revolutionize":                {"R2R"},
		"reverse-engineers-dream":                {"RED"},
		"reverse-engineering-in-software":        {"REiS"},
		"reverse-engineering-passion-team":       {"REPT"},
		"reviving-intelligent-fast-trading":      {"RiFT"},
		"revolution":                             {"RVL"},
		rampage:                                  {"RAMPAGE"},
		"rise-in-superior-couriering":            {"RiSC"},
		"risciso":                                {"RiSC"},
		"rom-1911":                               {"Razor 1911 CD-ROM Division"},
		"romkids":                                {"RMK"},
		"russian-trading-alliance":               {"RTA"},
		"sanxion":                                {"SXN"},
		"saints-and-sinners-group":               {"SSG"},
		"seek-n-destroy":                         {"SND"},
		"scene-charts":                           {"SC"},
		"skid-row":                               {"SR", "Skidrow"},
		"scoopex":                                {"SCX", "SPX"},
		"scooby-snack-magazine":                  {"SSM"},
		"scandal":                                {"SCL"},
		scud:                                     {"SCUD"},
		"scenenotice":                            {"SCN"},
		"scienide":                               {"SCi"},
		"sea-shell-commando":                     {"SSC"},
		"serials-2000":                           {"S2K"},
		"software-exchange":                      {"SEX", "SOFT-EX"},
		"silicon-dream-artists":                  {"SDA"},
		"shallow-grounds":                        {"SG"},
		"share-and-enjoy":                        {"SAE"},
		"shore-cracking-ansi-runners":            {"SCaR"},
		"shmeitcorp":                             {"Shmeit Corp", "SC"},
		"shitonlygerman":                         {"SOG", "Scheisse Deutsch Only"},
		"skillion":                               {"SKN"},
		"shiver":                                 {"SHV"},
		"siege":                                  {"SG"},
		"silent-cracking-force":                  {"SCF"},
		"silent-cracking-service":                {"SCS"},
		"sinister":                               {"SiN"},
		"slaves-of-pain":                         {"SoP"},
		"smokers-in-krime":                       {"SiK"},
		"smegma":                                 {"SMG"},
		"society-of-sharing":                     {"SOS"},
		"society-of-suckers":                     {"SOS"},
		"sodom":                                  {"SDM"},
		"solitudes":                              {"SLT"},
		"some-lonesome-ansi-makers":              {"SLAM"},
		"sorcerers":                              {"SOR"},
		"software-liberation-army":               {"SLA"},
		"software-pirating-coalition":            {"SPC"},
		"software-chronicles-digest":             {"SCD"},
		"software-in-danger":                     {"SID"},
		"software-pirates-inc":                   {"SPI"},
		"south-eastern-elite":                    {"SEE"},
		"spetznas":                               {"spetznaz"},
		"spazm":                                  {"SPZ", "SPZM", "Spazm/VGA"},
		"spazm-couriers":                         {"SPZ", "SPZM", "SPAZM"},
		"spectrum":                               {"SPEC"},
		"standards-of-piracy-association":        {"SPA"},
		"static":                                 {"STC"},
		"superior-art-creations":                 {"SAC"},
		"surprise-productions":                   {"SP"},
		"suicide-is-painless":                    {"SiP"},
		"synapse":                                {"SYN"},
		"syndicate-of-dreams":                    {"SOD"},
		"sysop-support-network":                  {"SSN"},
		"syndicate-network-of-couriers":          {"SYNC"},
		"sma-posse":                              {"$MA"},
		"the-syndicate":                          {"$ynd", "The $yndicate", "The $yndacite"},
		"talent-entertainment":                   {"TLN"},
		"tdu_jam":                                {"tdujam"},
		"team-edge":                              {"EDGE"},
		"team-technotrogens":                     {"TT3", "Team T3"},
		"technobrains":                           {"TCB"},
		"terratron":                              {"TERR"},
		"terror-zone-underground":                {"TZU"},
		"tekno-rage-ampersand-pirasoft":          {"TRPS"},
		"the-amatuer-crackist-tutorial":          {"ACT"}, //nolint:misspell
		"the-artists-guild":                      {"TAG"},
		"the-black-star":                         {"TBS"},
		"the-bitter-end":                         {"TBE"},
		"the-brain-slayer":                       {"TBS"},
		"the-buyers-group":                       {"TBG"},
		"the-brotherhood-of-gods-and-retards":    {"BGR"},
		"the-care-company":                       {"TCC"},
		"the-canadian-crackers":                  {"TCC"},
		"the-chronic-krackers":                   {"TCK"},
		"the-cracking-answer":                    {"TCA"},
		"the-crazed-asylum":                      {"TCA"},
		"the-cracking-clan":                      {"TCC"},
		"the-cradle-traders":                     {"TCT"},
		"the-codeblasters":                       {"TCB"},
		"the-console-division":                   {"TCD"},
		"the-corporation":                        {"CORP"},
		"the-council":                            {"CNC"},
		"the-courier-association":                {"TCA"},
		"the-cutting-edge":                       {"TCE"},
		"the-cracking-lords":                     {"TCL"},
		"the-damned-souls":                       {"TDS"},
		"the-dark-sector-courier-association":    {"TDSCA"},
		"the-defective-detectives":               {"TDD"},
		"the-dirty-dozen":                        {"TDD"},
		"the-dream-team":                         {"TDT"},
		"the-documentation-network":              {"TDN"},
		"the-dominators":                         {"DOM", "Dominators"},
		"the-elementals-piratelist":              {"TEP"},
		"the-elite-scripting-team":               {"TEST"},
		"the-entertainment-team":                 {"TET"},
		"the-elite-crew":                         {"TEC"},
		"the-faction":                            {"FACTION"},
		"the-firm":                               {"FiRM", "FRM"},
		"the-force-team":                         {"TFT"},
		"the-federation-of-software-theft":       {"FOST"},
		"the-fuck-you-crew":                      {"TFUC"},
		"the-gameboy-charts":                     {"GCharts"},
		"the-gamers-edge":                        {"TGE"},
		"the-game-review":                        {"TGR"},
		"the-game-scene-chart":                   {"TGSC"},
		"the-guild-of-thieves":                   {"TGT"},
		"the-grand-council":                      {"TGC"},
		"the-hardened-criminals":                 {"THC"},
		"the-hard-hackers":                       {"THH"},
		"the-hammer":                             {"MIR"},
		"the-hard-wares":                         {"THW"},
		"the-hill-people":                        {"THP"},
		"the-humble-guys":                        {"THG", "Humble"},
		"the-kiwi-killers":                       {"TKK"},
		"the-illinois-pirates":                   {"TIP"},
		"the-internet-dream-team":                {"TiDT"},
		"the-lamerz-group":                       {"TLG"},
		"the-inner-circle":                       {"TIC"},
		"the-lightning-crew":                     {"TLC"},
		"the-mappers-guild":                      {"TMG"},
		"the-missing-link":                       {"TML"},
		"the-millennium-group":                   {"TMG"},
		"the-mental-midgets":                     {"TMM"},
		"the-nameless-ones":                      {"TNO"},
		"the-naked-truth-magazine":               {"NTM"},
		"the-new-order-of-sacro_elite":           {"NOOSE"},
		"the-net-monkey-weekly-report":           {"TNMWR"},
		"the-north-west-connection":              {"TNWC"},
		"the-nova-team":                          {"TNT"},
		"the-one-and-only":                       {"TOAO"},
		"the-outlaws":                            {"TOL", "OL"},
		"the-other-side":                         {"TOS"},
		"the-pirate-syndicate":                   {"TPS"},
		"the-pirates-manifesto":                  {"Manifest"},
		"the-pirate-world":                       {"TPW"},
		"the-players-club":                       {"TPC"},
		"the-phoney-coders":                      {"TPC"},
		"the-phoney-coders-trainers-division":    {"TPC"},
		"the-people-upstairs":                    {"TPU"},
		"the-programmers-crew":                   {"TPC"},
		"the-rapeware-syndicate":                 {"TRWS"},
		"the-reversers-ultimate-epidemic":        {"tRUE"},
		"the-reviewers-guild":                    {"TRG"},
		"the-red-scorpion":                       {"TRS"},
		"the-reservoir-warez-report":             {"Report"},
		"the-sabotage-rebellion-hackers":         {"TSRh"},
		"the-safety-zone":                        {"TSZ"},
		"the-shining-darkness":                   {"TSD"},
		"the-space-pigs":                         {"SP"},
		"the-stealth-pirate-network":             {"TSPN"},
		"the-silents":                            {"TSL"},
		"the-silent-terror":                      {"TST"},
		"the-software-review":                    {"TSR"},
		"the-software-innovation-network":        {"SIN"},
		"the-sinister-syndicate":                 {"TSS"},
		"the-sure-logic-syndicate":               {"SLS"},
		"the-sysops-association-network":         {"TSAN"},
		"the-syndicate-of-original-gangsters":    {"TSOG", "OG SYND"},
		"the-unbiased-dox-report":                {"DR"},
		"the-underground-council":                {"UGC"},
		"the-underworld-corporation":             {"TUC"},
		"the-untouchables":                       {"UNT"},
		"the-warez-alliance":                     {"TWA"},
		"the-warez-report":                       {"Ware"},
		"the-warez-collectors":                   {"TWC"},
		"the-warez-magazine":                     {"Warez"},
		"the-week-in-warez":                      {"WWN"},
		"the-wondertwins":                        {"TWT"},
		"thg-fx":                                 {"The Humble Guys FX"},
		"tkc*crackers-in-action":                 {"tKC", "CiA"},
		"toads":                                  {"T.O.A.D.S."},
		"toxic":                                  {"TOX"},
		"trading-and-trading-international-crew": {"TATiC"},
		"tired-of-protection":                    {"TOP"},
		"triad":                                  {"TRI"},
		"trinity-of-triad":                       {"ToT"},
		"trinity-labs-incorporated":              {"TLI"},
		"tristar":                                {"TRS"},
		"tristar-ampersand-red-sector-inc":       {"TRSi", "TRS", "Tristar"},
		tlf:                                      {"TLF", "TRSi/Lightforce/Fusion"},
		"twilight":                               {"TW"},
		"twilight-zone":                          {"TZ"},
		"twilight-designs-crew":                  {"TDC"},
		"twin-sectors-inc":                       {"TSI"},
		"tyranny":                                {"TYR"},
		"twenty-one-twelve-bbs":                  {"2112", "²''²"},
		tsep:                                     {"TSEP"},
		"turbo-nutter-kiwi-bastards":             {"TNKB", "KiWi"},
		"ultra-tech":                             {"UT"},
		"ultra-tech*electro-magnetic-crackers":   {"UT-EMC"},
		"unified-legendary-traders-rising-again": {"ULTRA"},
		"ultra-force":                            {"UF", "Ultraforce"},
		"utilities-in-demand":                    {"UiD"},
		"under-seh-team":                         {"UST"},
		"underground-empire":                     {"UE"},
		"union":                                  {"UNi"},
		"united-albanian-reverse-engineers":      {"UARE"},
		"united-artist-association":              {"UAA"},
		"united-couriers":                        {"UC"},
		"united-cracking-force":                  {"UCF"},
		"universal-crackers-of-the-underground":  {"UCU"},
		"united-group-international":             {"UGI"},
		"united-reverse-engineering-team":        {"URET"},
		"united-software-association*fairlight":  {"USA/FLT"},
		"united-software-association":            {"USA"},
		"united-states-courier-report":           {"USCR"},
		"united-traders-of-germany":              {"UTG"},
		"united-file-traders":                    {"UFT"},
		"underpl":                                {"UPL"},
		"underground-kidz":                       {"UK"},
		"underground-pirating-syndicate":         {"UPS"},
		"unleashed":                              {"UNL"},
		"underground-cracking-syndicate":         {"UCS"},
		"unpacking-gods":                         {"UG"},
		"untouchables":                           {"UNT"},
		"untouchable-art":                        {"UNT"},
		"velocity-couriers":                      {"VEL"},
		"vendetta":                               {"VND"},
		"vengeance":                              {"VGN", "VEN", "Vengeance"},
		"vengeance-couriers":                     {"VGN"},
		"vertex":                                 {"VTX"},
		"very-strange-warez":                     {"VSW"},
		"victoria-independent-piracy":            {"VIP"},
		"vital-dox":                              {"VD"},
		"vision-factory":                         {"VF"},
		"visions-of-reality":                     {"VOR"},
		"virility":                               {"VRL"},
		"vitality":                               {"VIT", "VTL"},
		"vortex":                                 {"VXT"},
		"vortex-software":                        {"Vortex"},
		"warez-anarchy-review":                   {"WAR"},
		"worldwide-applications-release-system":  {"WARES"},
		"world-domination-force":                 {"WDF"},
		"wave":                                   {"The Wave", "CNC"},
		"western-area-pirates":                   {"WARP"},
		"warrior":                                {"WAR"},
		"wdyl-wtn":                               {"WDYL"},
		"west-coast-cracking-production":         {"WCCP"},
		"well-release-anything":                  {"WRA"},
		"wierd-new-world":                        {"WNW"}, //nolint:misspell
		"wild-cards":                             {"WC", "WC!"},
		"wicked":                                 {"WKD"},
		"wizard-couriers":                        {"WC"},
		"world-wide-couriers":                    {"WWC"},
		"xap":                                    {"EX Apple Pirates"},
		"x_large":                                {"XL"},
		"x_factor":                               {"XFactor"},
		"x_force":                                {"XF"},
		"xtreeme":                                {"XT"},
		"youngsters-against-mcafee":              {"YAM"},
		"ypogeios":                               {"YGS"},
		"zero-waiting-time":                      {"ZWT"},
		"zenith":                                 {"ZNTH"},
		"zick-zack-cooperation":                  {"ZZC"},
		"zone":                                   {"z0ne"},
	}
}

// Initialism returns the alternative spellings, acronyms and initialisms for the URL path.
// Or an empty slice if the URL path has no initialism.
//
// Example:
//
//	Initialism("the-firm") = []string{"FiRM, FRM"}
//	Initialism("defacto2") = []string{"DF2"}
func Initialism(path Path) []string {
	return Initialisms()[path]
}

// IsInitialism returns true if the URL path has an initialism.
//
// Example:
//
//	IsInitialism("the-firm") = true
//	IsInitialism("defacto2") = true
//	IsInitialism("some-random-bbs") = false
func IsInitialism(path Path) bool {
	_, match := Initialisms()[path]
	return match
}

// Join returns the alternative spellings, acronyms and initialisms for the
// URL path as a comma separated string.
// Or an empty string if the URL path has no initialism.
//
// Example:
//
//	Join("the-firm") = "FiRM, FRM"
//	Join("defacto2") = "DF2"
func Join(path Path) string {
	i := Initialism(path)
	if len(i) == 0 {
		return ""
	}
	return strings.Join(i, ", ")
}

// Match returns the list of initialisms that match the given string.
func Match(s string) []Path {
	var partials []Path
	for partial, values := range maps.All(Initialisms()) {
		for value := range slices.Values(values) {
			if strings.EqualFold(value, s) {
				partials = append(partials, partial)
			}
		}
	}
	return partials
}
